before_script:
  - apt-get update -qq
  - apt-get install xvfb -qq

stages:
  - build
  - package

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: 
    - Xvfb :99 -ac &
    - export DISPLAY=:99
    - mvn package -B
  artifacts:
    paths:
      - target/*.jar
