os:
    - linux

language: node_js
    - "10.15.0"

jdk:
    - openjdk8

env:
    - NODE_VERSION="10.15.0"

script: (mvn clean package -Pci -DskipTests)

branches:
    only:
        - develop
        - /^release\/.*$/

before_deploy:
    - export BUILD_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
    - export TRAVIS_TAG=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)-$(date +%Y%m%d%H%M%S)
    - export APP_ARTIFACT=$(find . -name comixed-app-*.zip)
###################################
# NOT GOING TO TAG THINGS FOR NOW #
###################################
#    - git config --local user.name "Darryl L. Pierce"
#    - git config --local user.email "mcpierce@gmail.com"
#    - git tag $TAG_NAME

deploy:
    - provider: releases
      api_key: $GITHUB_AUTH_TOKEN
      file_glob: true
      file:
        - ${APP_ARTIFACT}
      skip_cleanup: true
      keep-history: true
      overwrite: true
      on:
        branch: develop
    - provider: releases
      api_key: $GITHUB_AUTH_TOKEN
      file_glob: true
      file:
        - ${APP_ARTIFACT}
      skip_cleanup: true
      keep-history: true
      overwrite: true
      on:
        branch: release\/.*$/

cache:
    directories:
        - $HOME/.m2/repository
        - $TRAVIS_BUILD_DIR/comixed-web/node_modules
