on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout code
        uses: actions/checkout@master
      - name: Generate CHANGELOG.md
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release_branch: ${{ github.ref }}
          due_tag: v0.6.0-0.rc8
          since_tag: v0.5.2-2
      - name: Build project
        run: mvn package -Pci -DskipTests -Dassembly-name=RELEASE
      - name: Create SHA file.
        run: (cd comixed-app/target/artifacts; shasum comixed-app-0.6.0-0.rc8-RELEASE.zip > comixed-app-0.6.0-0.rc8.RELEASE.zip-sha)
      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            comixed-app/target/artifacts/comixed-app-0.6.0-0.rc8-RELEASE.zip
            comixed-app/target/artifacts/comixed-app-0.6.0-0.rc8.RELEASE.zip-sha
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
